name: CSV Transformation Workflow

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  transform-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' # Ensure this matches the version your script is compatible with

      - name: Install dependencies
        run: |
          pip install pandas requests

      - name: Download and Transform CSV
        run: python combo.py
        env:
          CSV_URL: ${{ secrets.CSV_URL }} # Ensure you've added your distributor's CSV URL as a secret

      - name: Commit and push if changes
        run: |
          git config --global user.email "mazzarolli.ai@gmail.com"
          git config --global user.name "Camarolli9979797"
          git add -A
          git commit -m "Updated CSV" || exit 0   # This won't fail if there's nothing to commit
          git -c http.extraheader="AUTHORIZATION: bearer ${{ secrets.MYSECRETKEY }}" push --set-upstream origin main
        env:
          MYSECRETKEY: ${{ secrets.MYSECRETKEY }} # This should be your PAT stored in GitHub Secrets

