name: CSV Transformation Workflow

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  transform-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9' # Use a Python version that is available in GitHub Actions runners.

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install pandas requests

      - name: Download and Transform CSV with combo.py
        run: python combo.py
        env:
          CSV_URL: 'https://feed.stockfirmati.com/csv/exportdropclang.csv'

      - name: Download and Transform CSV with brand.py
        run: python brand.py
        env:
          CSV_URL: 'https://feed.stockfirmati.com/csv/exportdropclang.csv'

      - name: Commit and push if changes
        run: |
          git config --global user.email "mazzarolli.ai@gmail.com"
          git config --global user.name "Camarolli9979797"
          git add -A
          git diff --staged --quiet || git commit -m "Updated CSV following transformation"
          git push
        env:
          GITHUB_TOKEN: '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'
